export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";
export const MESSAGE_FORM_API = "MESSAGE_FORM_API";
export const USER_LOADING = "USER_LOADING";
export const PRODUCT_ALL = "PRODUCT_ALL";
export const SET_SORT_PRODUCT = "SET_SORT_PRODUCT";

export const SCRAPING_FORM_API = "SCRAPING_FORM_API";
export const SCRAPING_PRODUCT_ALL = "SCRAPING_PRODUCT_ALL";
export const SET_SCRAPING_SORT_PRODUCT = "SET_SCRAPING_SORT_PRODUCT";
export const SET_SCRAPING_DELETE = "SET_SCRAPING_DELETE";
